name: fullter_webrtc_videocall_antor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.29.0
  firebase_database: ^10.5.1
  flutter_webrtc: ^0.10.3
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  permission_handler: ^10.2.0
  uuid: ^3.0.6
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true